# Generated by Django 5.1.1 on 2024-09-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIT', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('tipo_proveedor', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=50)),
                ('tipo_persona', models.CharField(choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], max_length=50)),
                ('beneficiarios', models.JSONField()),
                ('datos_bancarios', models.JSONField()),
                ('estado', models.CharField(default='Pendiente de Validación', max_length=20)),
            ],
        ),
    ]
